Repository CICE-Consortium/Icepack, pull requests merged in 2020-12, with the labels that each got.

#343 Move sw_redist, sw_frac, sw_dtemp from thermo namelist to shortwave namelist
  columnphysics/version.txt
  configuration/driver/icedrv_init.F90
  configuration/scripts/icepack_in
  doc/source/conf.py
  doc/source/user_guide/ug_case_settings.rst
Labels: Documentation, IO

#345 Update readthedocs requirements
  doc/requirements.txt
Labels: Documentation, Testing

#344 zsalinity test
  configuration/driver/icedrv_diagnostics_bgc.F90
  configuration/driver/icedrv_init_column.F90
  configuration/scripts/options/set_env.zsal
  configuration/scripts/options/set_nml.zsal
  configuration/scripts/tests/base_suite.ts
Labels: Priority: Medium, Testing, Thermodynamics, Type: Bug
