Repository CICE-Consortium/Icepack, pull requests merged in 2020-07, with the labels that each got.

#326 Shortwave redistribution option added to namelist.
  columnphysics/icepack_parameters.F90
  columnphysics/icepack_therm_bl99.F90
  columnphysics/icepack_therm_mushy.F90
  configuration/driver/icedrv_init.F90
  configuration/scripts/icepack_in
  configuration/scripts/options/set_nml.alt03
  configuration/scripts/options/set_nml.alt04
  configuration/scripts/options/set_nml.thermo1
  doc/source/icepack_index.rst
  doc/source/science_guide/sg_thermo.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Priority: High, Thermodynamics, Type: Feature

#327 clarify citation info in doc
  doc/source/intro/citing.rst
Labels: Documentation, Priority: Medium

#328 Snow melt computation bug.
  columnphysics/icepack_therm_vertical.F90
Labels: Type: Bug

#329 Update CPPs and Documentation
  columnphysics/icepack_isotope.F90
  columnphysics/icepack_kinds.F90
  configuration/scripts/icepack_decomp.csh
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_running.rst
  icepack.setup
Labels: Build, Documentation
