Repository CICE-Consortium/Icepack, pull requests merged in 2020-02, with the labels that each got.

#295 update izumi intel compiler after upgrade
  configuration/scripts/machines/env.izumi_intel
Labels: Porting, Priority: Medium

#296 Add conda environment, fix Makefile and Macros, implement `-nomodules`
  configuration/scripts/Makefile
  configuration/scripts/icepack.batch.csh
  configuration/scripts/machines/Macros.cheyenne_intel
  configuration/scripts/machines/Macros.conda_linux
  configuration/scripts/machines/Macros.conda_macos
  configuration/scripts/machines/Macros.testmachine_intel
  configuration/scripts/machines/env.conda_linux
  configuration/scripts/machines/env.conda_macos
  configuration/scripts/machines/environment.yml
  configuration/scripts/setup_run_dirs.csh
  doc/source/user_guide/ug_running.rst
  icepack.setup
Labels: Porting, Scripts

#298 Add adaptive timestepping for lateral melt and growth
  columnphysics/icepack_fsd.F90
  columnphysics/icepack_therm_itd.F90
  columnphysics/icepack_wavefracspec.F90
  doc/source/master_list.bib
  doc/source/science_guide/sg_itd.rst
Labels: Thermodynamics, Type: Feature

#299 Updates to wave fracture, including a bug fix
  columnphysics/icepack_fsd.F90
  columnphysics/icepack_therm_itd.F90
  columnphysics/icepack_wavefracspec.F90
  doc/source/science_guide/sg_itd.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Thermodynamics, Type: Bug, Type: Feature

#301 Update copyright and version number
  columnphysics/icepack_intfc.F90
  columnphysics/version.txt
  configuration/driver/icedrv_MAIN.F90
  doc/source/conf.py
  doc/source/intro/copyright.rst
Labels: Documentation, Priority: High

#302 Add initialization of n_aero to icepack driver
  configuration/driver/icedrv_init.F90
Labels: Driver/Interface, Priority: High, Type: Bug
