Repository CICE-Consortium/Icepack, pull requests merged in 2021-03, with the labels that each got.

#349 Update Copyright to 2021
  columnphysics/icepack_intfc.F90
  configuration/driver/icedrv_MAIN.F90
  doc/source/conf.py
  doc/source/intro/copyright.rst
Labels: Documentation, Priority: Medium

#350 update LICENSE.pdf
  LICENSE.pdf
Labels: Documentation

#352 modify error tolerance for rare mushy thermo failure
  columnphysics/icepack_therm_vertical.F90
Labels: Priority: Low, Thermodynamics, Type: Bug

#337 Added catch for unusual case of (hicen_init(n+1) - hicen_init(n))>0
  columnphysics/icepack_therm_itd.F90
Labels: Priority: Medium, Type: Bug

#353 Addition of CompyMcNodeFace to Icepack machine files
  configuration/scripts/icepack.batch.csh
  configuration/scripts/machines/Macros.compy_intel
  configuration/scripts/machines/env.compy_intel
Labels: Build, Porting, Scripts

#356 Update Compy
  configuration/scripts/icepack.batch.csh
  configuration/scripts/machines/env.compy_intel
Labels: Porting

#331 Documentation on adding diagnostic output.
  doc/source/developer_guide/dg_adding_diagnostics.rst
  doc/source/developer_guide/index.rst
  doc/source/science_guide/sg_thermo.rst
Labels: Documentation, Priority: Medium, Type: Feature

#355 move shortwave absorbed in negligible snow layers to surface
  columnphysics/icepack_shortwave.F90
  columnphysics/icepack_therm_mushy.F90
Labels: Priority: Medium, Thermodynamics, Type: Bug

#358 Update version number and revise reference
  columnphysics/version.txt
  doc/source/conf.py
  doc/source/master_list.bib
Labels: Documentation
