Repository CICE-Consortium/Icepack, pull requests merged in 2023-08, with the labels that each got.

#449 Updates to advanced snow physics implementation
  columnphysics/icepack_flux.F90
  columnphysics/icepack_itd.F90
  columnphysics/icepack_snow.F90
  columnphysics/icepack_therm_itd.F90
  columnphysics/icepack_therm_mushy.F90
  columnphysics/icepack_therm_vertical.F90
  columnphysics/icepack_tracers.F90
  configuration/driver/icedrv_init.F90
  configuration/driver/icedrv_step.F90
  configuration/scripts/icepack.batch.csh
  configuration/scripts/machines/Macros.badger_intel
  configuration/scripts/machines/Macros.chicoma_intel
  configuration/scripts/machines/env.badger_intel
  configuration/scripts/machines/env.chicoma_intel
Labels: Type: Bug, Priority: Extreme

#448 Deprecate zsalinity
  columnphysics/icepack_brine.F90
  columnphysics/icepack_intfc.F90
  columnphysics/icepack_itd.F90
  columnphysics/icepack_mechred.F90
  columnphysics/icepack_parameters.F90
  columnphysics/icepack_therm_bl99.F90
  columnphysics/icepack_therm_itd.F90
  columnphysics/icepack_tracers.F90
  columnphysics/icepack_zbgc.F90
  columnphysics/icepack_zbgc_shared.F90
  columnphysics/icepack_zsalinity.F90
  configuration/driver/icedrv_InitMod.F90
  configuration/driver/icedrv_RunMod.F90
  configuration/driver/icedrv_arrays_column.F90
  configuration/driver/icedrv_diagnostics_bgc.F90
  configuration/driver/icedrv_domain_size.F90
  configuration/driver/icedrv_flux.F90
  configuration/driver/icedrv_init_column.F90
  configuration/driver/icedrv_restart.F90
  configuration/driver/icedrv_restart_bgc.F90
  configuration/driver/icedrv_step.F90
  configuration/scripts/icepack.build
  configuration/scripts/icepack.settings
  configuration/scripts/options/set_env.bgcispol
  configuration/scripts/options/set_env.bgcnice
  configuration/scripts/options/set_env.bgcsklnice
  configuration/scripts/options/set_env.zsal
  configuration/scripts/options/set_nml.zsal
  doc/source/developer_guide/dg_adding_diagnostics.rst
  doc/source/developer_guide/dg_col_phys.rst
  doc/source/user_guide/interfaces.include
  doc/source/user_guide/lg_protocols.rst
  doc/source/user_guide/lg_sequence.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Physics

#454 Corrects thin ice/snow treatment of enthalpy and other tracers
  columnphysics/icepack_therm_shared.F90
  columnphysics/icepack_therm_vertical.F90
Labels: Thermodynamics
