Repository CICE-Consortium/Icepack, pull requests merged in 2023-10, with the labels that each got.

#460 Merge E3SM Icepack cice-consortium/E3SM-icepack-initial-integration to Consortium
  columnphysics/icepack_brine.F90
  columnphysics/icepack_intfc.F90
  columnphysics/icepack_itd.F90
  columnphysics/icepack_mechred.F90
  columnphysics/icepack_meltpond_lvl.F90
  columnphysics/icepack_mushy_physics.F90
  columnphysics/icepack_orbital.F90
  columnphysics/icepack_parameters.F90
  columnphysics/icepack_shortwave.F90
  columnphysics/icepack_shortwave_data.F90
  columnphysics/icepack_therm_bl99.F90
  columnphysics/icepack_therm_itd.F90
  columnphysics/icepack_therm_mushy.F90
  columnphysics/icepack_therm_shared.F90
  columnphysics/icepack_therm_vertical.F90
  columnphysics/icepack_tracers.F90
  columnphysics/icepack_warnings.F90
  configuration/driver/icedrv_InitMod.F90
  configuration/driver/icedrv_arrays_column.F90
  configuration/driver/icedrv_calendar.F90
  configuration/driver/icedrv_forcing.F90
  configuration/driver/icedrv_init.F90
  configuration/driver/icedrv_init_column.F90
  configuration/driver/icedrv_restart.F90
  configuration/driver/icedrv_step.F90
  configuration/scripts/icepack.build
  configuration/scripts/icepack.settings
  configuration/scripts/icepack_in
  configuration/scripts/options/set_env.mpassi
  configuration/scripts/options/set_env.snicar
  configuration/scripts/options/set_env.snicartest
  configuration/scripts/options/set_nml.alt03
  configuration/scripts/options/set_nml.alt04
  configuration/scripts/options/set_nml.bgcispol
  configuration/scripts/options/set_nml.bgcnice
  configuration/scripts/options/set_nml.bgcsklnice
  configuration/scripts/options/set_nml.fsd12
  configuration/scripts/options/set_nml.leap
  configuration/scripts/options/set_nml.modal
  configuration/scripts/options/set_nml.mpassi
  configuration/scripts/options/set_nml.snicar
  configuration/scripts/options/set_nml.snicartest
  configuration/scripts/options/set_nml.thermo1
  configuration/scripts/tests/snicar_suite.ts
  doc/source/icepack_index.rst
  doc/source/master_list.bib
  doc/source/science_guide/sg_thermo.rst
  doc/source/user_guide/interfaces.include
  doc/source/user_guide/ug_case_settings.rst
  doc/source/user_guide/ug_testing.rst
  icepack.setup
Labels: Driver/Interface, Thermodynamics

#464 Re-add Picard Nonconvergence Diagnostics
  columnphysics/icepack_therm_mushy.F90
Labels: Analysis

#465 icepack_parameters: don't recompute constants in icepack_query_parameters
  columnphysics/icepack_parameters.F90
Labels: Software Engineering

#467 Port to Perlmutter gnu, intel, cray.
  configuration/scripts/icepack.batch.csh
  configuration/scripts/icepack.launch.csh
  configuration/scripts/machines/Macros.perlmutter_cray
  configuration/scripts/machines/Macros.perlmutter_gnu
  configuration/scripts/machines/Macros.perlmutter_intel
  configuration/scripts/machines/env.perlmutter_cray
  configuration/scripts/machines/env.perlmutter_gnu
  configuration/scripts/machines/env.perlmutter_intel
Labels: Porting

#468 Remove _old options for tfrz_option
  columnphysics/icepack_therm_shared.F90
  columnphysics/icepack_tracers.F90
  configuration/scripts/options/set_nml.alt03
  configuration/scripts/options/set_nml.alt04
  configuration/scripts/options/set_nml.bgcispol
  configuration/scripts/options/set_nml.bgcnice
  configuration/scripts/options/set_nml.bgcsklnice
  configuration/scripts/options/set_nml.fsd12
  configuration/scripts/options/set_nml.leap
  configuration/scripts/options/set_nml.modal
  configuration/scripts/options/set_nml.thermo1
Labels: Forcing, Physics

#469 Change CPP USE_SNICARHC to NO_SNICARHC
  columnphysics/icepack_shortwave_data.F90
  configuration/scripts/icepack.build
  doc/source/user_guide/ug_case_settings.rst
Labels: Build

#471 Update Derecho inputdata path, point to campaign
  configuration/scripts/machines/env.derecho_cray
  configuration/scripts/machines/env.derecho_gnu
  configuration/scripts/machines/env.derecho_intel
  configuration/scripts/machines/env.derecho_intelclassic
  configuration/scripts/machines/env.derecho_inteloneapi
  configuration/scripts/machines/env.derecho_nvhpc
Labels: Porting

#470 Clarify documentation associated with namelist inputs
  doc/source/icepack_index.rst
  doc/source/user_guide/ug_case_settings.rst
Labels: Documentation

#472 Update 5-band dEdd to support test data
  columnphysics/icepack_shortwave.F90
  columnphysics/icepack_shortwave_data.F90
  configuration/scripts/options/set_env.snicar
  configuration/scripts/options/set_env.snicartest
  configuration/scripts/tests/base_suite.ts
  configuration/scripts/tests/snicar_suite.ts
Labels: Testing, Software Engineering

#474 use -puny in denominator of scaling ratio for flux limiting
  columnphysics/icepack_therm_vertical.F90
Labels: Type: Bug

#473 Update version, interface documentation, remove trailing blanks
  columnphysics/icepack_itd.F90
  columnphysics/icepack_mechred.F90
  columnphysics/icepack_shortwave.F90
  columnphysics/icepack_therm_itd.F90
  columnphysics/icepack_therm_vertical.F90
  columnphysics/version.txt
  configuration/driver/icedrv_forcing.F90
  configuration/driver/icedrv_init_column.F90
  doc/source/conf.py
  doc/source/user_guide/interfaces.include
Labels: Documentation

#475 Fix icepack.launch.csh
  configuration/scripts/icepack.launch.csh
Labels: Scripts
